apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app-deployment
spec:
  replicas: 2  # Number of instances you want to run
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: nodeapp  # Node.js app's Docker image and tag
          ports:
            - containerPort: 3000  # Port your Node.js app is listening on
